backport 1.x:
  - "*"
  - "*/*"
  - "*/**/*"
  - "*/**/**/*"
  - "*/**/**/**/*"
  - "*/**/**/**/**/*"
  - "*/**/**/**/**/**/*"
  - "*/**/**/**/**/**/**/*"
  - "*/**/**/**/**/**/**/**/*"
  - "*/**/**/**/**/**/**/**/**/*"
  - ".github/**/*"

github actions:
  - ".github/**/*"

documentation:
  - "*.md"
  - "release-notes/*"
  - "docs/*"

infra:
  - "build.gradle"
